# Reading Dataset

In [124]:
import pandas as pd

df = pd.read_csv('services_provided_to_population.csv')
df.head(10)

,Year,Unnamed: 1,Əhaliyə göstərilən ödənişli xidmətlərin ümumi həcmində məişət xidmətinin həcmi (min manat),Əhaliyə göstərilən ödənişli xidmətlərin ümumi həcmində nəqliyyat xidmətinin həcmi (min manat),Əhaliyə göstərilən ödənişli xidmətlərin ümumi həcmində rabitə xidmətinin həcmi (min manat),Əhaliyə göstərilən ödənişli xidmətlərin ümumi həcmində mənzil təsərrüfatı xidmətlərinin həcmi (min manat),Əhaliyə göstərilən ödənişli xidmətlərin ümumi həcmində kommunal təsərrüfatı xidmətlərinin həcmi (min manat),Əhaliyə göstərilən ödənişli xidmətlərin ümumi həcmində mədəniyyət xidmətlərinin həcmi (min manat),Əhaliyə göstərilən ödənişli xidmətlərin ümumi həcmində turist-ekskursiya xidmətlərinin həcmi (min manat),Əhaliyə göstərilən ödənişli xidmətlərin ümumi həcmində bədən tərbiyəsi və idman xidmətinin həcmi (min manat),Əhaliyə göstərilən ödənişli xidmətlərin ümumi həcmində səhiyyə xidmətlərin həcmi (min manat),Əhaliyə göstərilən ödənişli xidmətlərin ümumi həcmində sanatoriya-kurort və sağlamlıq xidmələrinin həcmi (min manat),Əhaliyə göstərilən ödənişli xidmətlərin ümumi həcmində hüquq səciyyəli və bank xidmətlərinin həcmi (min manat),Əhaliyə göstərilən ödənişli xidmətlərin ümumi həcmində təhsil xidmətlərinin həcmi (min manat),Əhaliyə göstərilən ödənişli xidmətlərin ümumi həcmində məktəbəqədər təhsil xidmətlərinin həcmi (min manat),Əhaliyə göstərilən ödənişli xidmətlərin ümumi həcmində ali və orta təhsil xidmətlərinin həcmi (min manat),Əhaliyə göstərilən ödənişli xidmətlərin ümumi həcmində əhalinin kurslarda öyrədilməsi xidmətlərinin həcmi (min manat),Əhaliyə göstərilən ödənişli xidmətlərin ümumi həcmində sair ödənişli xidmətlərin həcmi (min manat)
0,2024,NaN,12885471.3,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
1,2023,NaN,1262802.6,1986014.2,2520751.3,222914.5,2292041.7,73129.7,269024.8,53859.2,939027.9,87551.1,341787.5,951238.6,33215.2,494288.4,423735.0,411465.7
2,2022,NaN,987446.6,1429595.8,2219907.5,147036.7,2141886.9,61281.9,193469.7,42705.9,687280.6,66839.4,285369.6,660478.6,19198.4,335084.7,306195.5,330115.3
3,2021,NaN,819913.1,1080071.5,2101220.9,122333.4,1729189.5,55608.8,121013.6,35706.9,617042.5,44253.1,264359.3,476532.7,12571.6,244591.8,219369.3,290941.3
4,2020,NaN,756064.7,1046580.9,1933045.9,110272.6,1469369.1,45434.3,85651.6,25913.6,548927.6,31628.7,251256.3,425553.1,10919.3,223225.1,191408.7,268675.9
5,2019,NaN,1021799.3,1838622.9,1903553.5,204934.1,1432338.7,218385.1,356895.9,88762.1,571362.3,110257.9,435785.6,746909.7,38352.3,318657.8,389899.6,677651.6
6,2018,NaN,991319.0,1776447.3,1864401.1,196347.3,1378235.2,209156.2,294995.2,83587.3,504473.1,104753.5,422910.7,679620.5,34613.2,290486.4,354520.9,625512.2
7,2017,NaN,959087.4,1695451.1,1766598.0,185161.5,1326580.7,202616.3,233316.5,78748.1,453856.1,99051.3,455722.7,615564.9,31393.8,259152.8,325018.3,564281.2
8,2016,NaN,896486.8,1538521.9,1655668.2,164004.9,1202702.4,179624.4,195243.9,67944.9,382678.0,85907.3,413917.1,546682.9,24913.8,235510.8,286258.3,480373.0
9,2015,NaN,863114.6,1460499.2,1620765.7,176866.1,1060129.2,158847.9,181188.2,64537.2,310647.1,92947.5,453140.3,531864.7,23030.7,226923.7,281910.3,488217.5

# Dataset Cleaning and Processing

- Dropping irrelevant columns, rows and resetting the index
- Renaming columns
- Converting data types to `float64` for numerical analysis
- Dataset understanding (`df.describe`, `df.info`)
- Feature Engineering: Creating a `Total` volume and an `Education_total` aggregate.

In [125]:
df = df.drop(columns='Unnamed: 1')
df = df.drop(0).reset_index(drop=True)

In [126]:
rename_map = {
    "Year": "Year",
    "Əhaliyə göstərilən ödənişli xidmətlərin ümumi həcmində məişət xidmətinin həcmi (min manat)": "Household",
    "Əhaliyə göstərilən ödənişli xidmətlərin ümumi həcmində nəqliyyat xidmətinin həcmi (min manat)": "Transportation",
    "Əhaliyə göstərilən ödənişli xidmətlərin ümumi həcmində rabitə xidmətinin həcmi (min manat)": "Communication",
    "Əhaliyə göstərilən ödənişli xidmətlərin ümumi həcmində mənzil təsərrüfatı xidmətlərinin həcmi (min manat)": "Housing",
    "Əhaliyə göstərilən ödənişli xidmətlərin ümumi həcmində kommunal təsərrüfatı xidmətlərinin həcmi (min manat)": "Utilities",
    "Əhaliyə göstərilən ödənişli xidmətlərin ümumi həcmində mədəniyyət xidmətlərinin həcmi (min manat)": "Culture",
    "Əhaliyə göstərilən ödənişli xidmətlərin ümumi həcmində turist-ekskursiya xidmətlərinin həcmi (min manat)": "Tourism",
    "Əhaliyə göstərilən ödənişli xidmətlərin ümumi həcmində bədən tərbiyəsi və idman xidmətinin həcmi (min manat)": "Sports",
    "Əhaliyə göstərilən ödənişli xidmətlərin ümumi həcmində səhiyyə xidmətlərin həcmi (min manat)": "Healthcare",
    "Əhaliyə göstərilən ödənişli xidmətlərin ümumi həcmində sanatoriya-kurort və sağlamlıq xidmələrinin həcmi (min manat)": "Health",
    "Əhaliyə göstərilən ödənişli xidmətlərin ümumi həcmində hüquq səciyyəli və bank xidmətlərinin həcmi (min manat)": "Legal_Banking",
    "Əhaliyə göstərilən ödənişli xidmətlərin ümumi həcmində təhsil xidmətlərinin həcmi (min manat)": "Education_General",
    "Əhaliyə göstərilən ödənişli xidmətlərin ümumi həcmində məktəbəqədər təhsil xidmətlərinin həcmi (min manat)": "Education_Preschool",
    "Əhaliyə göstərilən ödənişli xidmətlərin ümumi həcmində ali və orta təhsil xidmətlərinin həcmi (min manat)": "Education_Higher_Secondary",
    "Əhaliyə göstərilən ödənişli xidmətlərin ümumi həcmində əhalinin kurslarda öyrədilməsi xidmətlərinin həcmi (min manat)": "Education_Courses",
    "Əhaliyə göstərilən ödənişli xidmətlərin ümumi həcmində sair ödənişli xidmətlərin həcmi (min manat)": "Other"
}

df = df.rename(columns=rename_map)
df.head()

,Year,Household,Transportation,Communication,Housing,Utilities,Culture,Tourism,Sports,Healthcare,Health,Legal_Banking,Education_General,Education_Preschool,Education_Higher_Secondary,Education_Courses,Other
0,2023,1262802.6,1986014.2,2520751.3,222914.5,2292041.7,73129.7,269024.8,53859.2,939027.9,87551.1,341787.5,951238.6,33215.2,494288.4,423735.0,411465.7
1,2022,987446.6,1429595.8,2219907.5,147036.7,2141886.9,61281.9,193469.7,42705.9,687280.6,66839.4,285369.6,660478.6,19198.4,335084.7,306195.5,330115.3
2,2021,819913.1,1080071.5,2101220.9,122333.4,1729189.5,55608.8,121013.6,35706.9,617042.5,44253.1,264359.3,476532.7,12571.6,244591.8,219369.3,290941.3
3,2020,756064.7,1046580.9,1933045.9,110272.6,1469369.1,45434.3,85651.6,25913.6,548927.6,31628.7,251256.3,425553.1,10919.3,223225.1,191408.7,268675.9
4,2019,1021799.3,1838622.9,1903553.5,204934.1,1432338.7,218385.1,356895.9,88762.1,571362.3,110257.9,435785.6,746909.7,38352.3,318657.8,389899.6,677651.6

In [127]:
for col in df.columns:
    if col != 'Year':
        df[col] = df[col].astype('float64')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 17 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Year                        29 non-null     int64
 1   Household                   29 non-null     float64
 2   Transportation              29 non-null     float64
 3   Communication               29 non-null     float64
 4   Housing                     29 non-null     float64
 5   Utilities                   29 non-null     float64
 6   Culture                     29 non-null     float64
 7   Tourism                     29 non-null     float64
 8   Sports                      29 non-null     float64
 9   Healthcare                  29 non-null     float64
 10  Health                      29 non-null     float64
 11  Legal_Banking               29 non-null     float64
 12  Education_General           29 non-null     float64
 13  Education_Preschool         29 non-null     float64
 14  Education_Higher_Secondary  29 non-null     float64
 15  Education_Courses           29 non-null     float64
 16  Other                       29 non-null     float64
dtypes: float64(16), int64(1)
memory usage: 4.0 KB

In [128]:
df.describe().round(2)

,Year,Household,Transportation,Communication,Housing,Utilities,Culture,Tourism,Sports,Healthcare,Health,Legal_Banking,Education_General,Education_Preschool,Education_Higher_Secondary,Education_Courses,Other
count,29.00,29.00,29.00,29.00,29.00,29.00,29.00,29.00,29.00,29.00,29.00,29.00,29.00,29.00,29.00,29.00,29.00
mean,2009.00,519578.72,782084.53,978522.64,96507.85,705538.64,71670.19,100059.34,29413.09,218264.90,42827.06,195744.59,288239.08,12137.84,139708.89,136392.37,252737.16
std,8.51,375080.21,672014.87,817002.36,76875.75,687365.16,72249.87,99821.91,29761.03,261913.38,38914.01,176069.38,282364.78,11861.79,129303.93,144658.35,204741.07
min,1995.00,29490.00,57867.40,6757.00,2998.60,4922.40,342.80,500.40,31.20,379.20,2107.60,3478.20,1537.40,86.60,1255.20,195.60,1894.60
25%,2002.00,132230.20,95906.80,139663.00,12398.00,74511.60,5780.60,16406.00,863.60,7010.80,4107.80,8197.00,26456.20,1541.80,21821.40,3182.60,52537.80
50%,2009.00,547058.70,788369.30,936775.10,122333.40,584370.00,55608.80,79124.00,25913.60,98501.00,44253.10,200047.00,235243.50,10919.30,134390.00,70242.00,268675.90
75%,2016.00,819913.10,1396270.70,1655668.20,155613.50,1202702.40,120641.00,156466.50,52777.90,382678.00,81891.70,341787.50,484835.70,19198.40,226923.70,252260.00,411465.70
max,2023.00,1262802.60,1986014.20,2520751.30,222914.50,2292041.70,218385.10,356895.90,88762.10,939027.90,110257.90,455722.70,951238.60,38352.30,494288.40,423735.00,677651.60

In [129]:
education_cols = ['Education_General', 'Education_Preschool', 'Education_Higher_Secondary', 'Education_Courses']
df['Education_total'] = df[education_cols].sum(axis=1)
sector_cols = [
    'Household', 'Transportation', 'Communication', 'Housing',
    'Utilities', 'Culture', 'Tourism', 'Sports',
    'Healthcare', 'Health', 'Legal_Banking', 'Education_total',
    'Other'
]
df['Total'] = df[sector_cols].sum(axis=1)
df.head()

,Year,Household,Transportation,Communication,Housing,Utilities,Culture,Tourism,Sports,Healthcare,Health,Legal_Banking,Education_General,Education_Preschool,Education_Higher_Secondary,Education_Courses,Other,Education_total,Total
0,2023,1262802.6,1986014.2,2520751.3,222914.5,2292041.7,73129.7,269024.8,53859.2,939027.9,87551.1,341787.5,951238.6,33215.2,494288.4,423735.0,411465.7,1902477.2,12362847.4
1,2022,987446.6,1429595.8,2219907.5,147036.7,2141886.9,61281.9,193469.7,42705.9,687280.6,66839.4,285369.6,660478.6,19198.4,335084.7,306195.5,330115.3,1320957.2,9913893.1
2,2021,819913.1,1080071.5,2101220.9,122333.4,1729189.5,55608.8,121013.6,35706.9,617042.5,44253.1,264359.3,476532.7,12571.6,244591.8,219369.3,290941.3,953065.4,8234719.3
3,2020,756064.7,1046580.9,1933045.9,110272.6,1469369.1,45434.3,85651.6,25913.6,548927.6,31628.7,251256.3,425553.1,10919.3,223225.1,191408.7,268675.9,851106.2,7423927.4
4,2019,1021799.3,1838622.9,1903553.5,204934.1,1432338.7,218385.1,356895.9,88762.1,571362.3,110257.9,435785.6,746909.7,38352.3,318657.8,389899.6,677651.6,1493819.4,10354168.4

### I removed the `Total` and education sub-categories from this view to prevent scale from being distorted, allowing a clear comparison between the main sectors.

In [130]:
removed_features_plot = education_cols.copy()
removed_features_plot.append('Total')
df_plot = df.set_index('Year').sort_index().drop(columns=removed_features_plot)

# Exploratory Data Analysis (EDA)

In [131]:
import plotly.express as px

graph = px.line(df_plot, 
                title='Total Paid Services Provided to Population',
                labels={'value': 'Volume', 'Year': 'Year'},
                markers=True,
                width=1400, 
                height=800)
graph.update_layout(yaxis_tickformat='.3s', legend_title_text='Sectors')
graph.update_traces(
    hovertemplate="Sector: %{fullData.name}<br>Year: %{x}<br>Volume: %{y:.3s}<extra></extra>"
)
graph.show()

In [132]:
# Creating the pie chart for distribution
sector_totals = df[sector_cols].sum()
graph = px.pie(
    values=sector_totals.values, 
    names=sector_totals.index, 
    title='Distribution of Paid Services by Sector',
    width=900, 
    height=900
)
graph.update_layout(legend_title_text='Sectors')
graph.show()

In [133]:
# Creating the bar chart
graph = px.bar(df, 
             x='Year', 
             y='Total', 
             title='Total Paid Services Over the Years',
             width=1200, 
             height=500)

graph.update_layout(yaxis_tickformat='.3s')
graph.show()

### Pre vs. Post COVID-19 Analysis

In [134]:
df = df.sort_values('Year')
df_pre = df[df['Year'] < 2020]
df_post = df[df['Year'] >= 2020]
pre_growth = df_pre[sector_cols].pct_change().median() * 100
pre_growth = pre_growth.sort_values(ascending=False)
post_growth = df_post[sector_cols].pct_change().median() * 100
post_growth = post_growth.sort_values(ascending=False)

In [135]:
from plotly.subplots import make_subplots
import plotly.graph_objects as go

# Creating the layout
graph = make_subplots(
    rows=2, cols=1, 
    subplot_titles=('Median Annual Growth Rate by Sector (Before COVID)', 
                    'Median Annual Growth Rate by Sector (After COVID)')
)

# Adding the bars to the layout
graph.add_trace(go.Bar(x=pre_growth.index, y=pre_growth.values), row=1, col=1)
graph.add_trace(go.Bar(x=post_growth.index, y=post_growth.values), row=2, col=1)

# Formatting the table by setting dimensions, and also fixed x and y axis range
graph.update_layout(
    height=1000, 
    width=1200, 
    showlegend=False,
    # This locks the top chart
    xaxis_fixedrange=True, 
    yaxis_fixedrange=True,
    # This locks the bottom chart
    xaxis2_fixedrange=True, 
    yaxis2_fixedrange=True
)

# I set the Y-axis range and format for both subplots for comparison
graph.update_yaxes(range=[0, 50], tickformat=".2f", ticksuffix="%", row=1, col=1)
graph.update_yaxes(range=[0, 50], tickformat=".2f", ticksuffix="%", row=2, col=1)

graph.show()

In [136]:
# Calculating the percentage change between 2019 and 2020
df_covid = df[df['Year'].isin([2019, 2020])].sort_values('Year')
covid_impact = df_covid[sector_cols].pct_change() * 100
# Taking the results and sorting them to see which sectors were hit hardest
covid_impact = covid_impact.iloc[1].sort_values()
# Creating the bar chart to visualize impact rate on each sector
fig = px.bar(x=covid_impact.index, 
             y=covid_impact.values,
             title='COVID Impact on Sectors',
             labels={'x':'Sectors', 'y':'Impact Rate (%)'},
             width=1500, 
             height=700)
# Adding a red line at 0 to show the baseline clearly
fig.add_hline(y=0, line_color="red")
# Setting the y-axis range to show the drop and fixed the axis to keep it stable
fig.update_layout(yaxis=dict(range=[5, -100], tickformat=".3s", ticksuffix="%"))
fig.update_layout(xaxis_fixedrange=True, yaxis_fixedrange=True)
fig.show()

In [137]:
yoy_growth = df[sector_cols].pct_change() * 100  # Year-over-Year growth percentage for all sectors
corr_matrix = yoy_growth.corr() # Creating the corr matrix
corr_matrix = corr_matrix.round(2)  # Rounding decimal numbers to make it easier to read

In [138]:
# Creating the heatmap to visualize
graph = px.imshow(
    corr_matrix, 
    text_auto='.2f', 
    color_continuous_scale='RdBu_r', 
    title='Correlation Between Sector Growth Rates',
    width=1000, 
    height=900)
# Applying fixed range and a custom hovertemplate
graph.update_layout(xaxis_fixedrange=True, yaxis_fixedrange=True)
graph.update_traces(hovertemplate="Sector X: %{x}<br>Sector Y: %{y}<br>Correlation: %{z}<extra></extra>")
graph.show()

### 10-Year Growth Forecasting (Using Log-Linear Regression Model)

In [139]:
import numpy as np
import pandas as pd
import plotly.express as px
from sklearn.linear_model import LinearRegression

# 1. Preparing Data for next 10 years starting from 2026
X = df[['Year']].values
future_years = np.array(range(2026, 2036)).reshape(-1, 1)
forecast_results = {'Year': future_years.flatten()}

# 2. Simple Loop for Predictions
for sector in sector_cols:
    y_log = np.log1p(df[sector].values)
    model = LinearRegression().fit(X, y_log)
    forecast_results[sector] = np.expm1(model.predict(future_years))

forecast_df = pd.DataFrame(forecast_results)

In [140]:
# Creating the line graph to visualize it
graph = px.line(forecast_df, 
              x='Year', 
              y=sector_cols,
              title='10-Year Service Sector Volume Forecast (Log-Linear Regression)',
              labels={'value':'Volume', 'Year':'Year'},
              markers=True,
              width=1500, 
              height=900)

# Applying fixed layout and custom hovertemplate
graph.update_layout(
    yaxis_tickformat='.3s', 
    xaxis_fixedrange=True,  
    yaxis_fixedrange=True,   
    legend_title_text='Sectors')

graph.update_traces(hovertemplate="Sector: %{fullData.name}<br>Year: %{x}<br>Volume: %{y}<extra></extra>")
graph.show()